apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  name: main-lb
spec:
  type: NodePort
  selector: {{ toYaml .Values.podLabels | nindent 4 }}
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: {{ .Values.ports.name }}
      nodePort: 30010